using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CapaEntidad;

namespace CapaDatos
{
    public class CD_Brands
    {
        public List<Brand> ListBrands()
        {
            List<Brand> newList = new List<Brand>();

            try
            {
                using (SqlConnection connection = new SqlConnection(Connection.cn))
                {
                    string query = "SELECT IdBrand,Description,Active from BRAND";
                    SqlCommand cmd = new SqlCommand(query, connection);
                    cmd.CommandType = CommandType.Text;

                    connection.Open();

                    using (SqlDataReader dr = cmd.ExecuteReader())
                    {
                        while (dr.Read())
                        {
                            newList.Add(
                                new Brand()
                                {
                                    IdBrand = Convert.ToInt32(dr["IdBrand"]),
                                    Description = dr["Description"].ToString(),
                                    Active = Convert.ToBoolean(dr["Active"])
                                }
                            );
                        }
                    }
                }
            }
            catch
            {
                newList = new List<Brand>();
            }
            return newList;
        }


        public int RegisterBrand(Brand newBrand, out string Message)
        {
            int idAutoGenerated = 0;
            Message = string.Empty;
            try
            {
                using (SqlConnection oconnection = new SqlConnection(Connection.cn))
                {
                    SqlCommand cmd = new SqlCommand("sp_RegisterBrand", oconnection);
                    cmd.Parameters.AddWithValue("Description", newBrand.Description);
                    cmd.Parameters.AddWithValue("Active", newBrand.Active);
                    cmd.Parameters.Add("Result", SqlDbType.Int).Direction = ParameterDirection.Output;
                    cmd.Parameters.Add("Message", SqlDbType.VarChar, 500).Direction = ParameterDirection.Output;
                    cmd.CommandType = CommandType.StoredProcedure;

                    oconnection.Open();

                    cmd.ExecuteNonQuery();

                    idAutoGenerated = Convert.ToInt32(cmd.Parameters["Result"].Value);
                    Message = cmd.Parameters["Message"].ToString() == "Message" ? "Error de servidor" : cmd.Parameters["Message"].ToString();
                }

            }
            catch (Exception e)
            {
                idAutoGenerated = 0;
                Message = e.Message;
            }
            return idAutoGenerated;
        }

        public bool EditBrand(Brand brandToEdit, out string Message)
        {
            bool result = false;
            Message = string.Empty;
            try
            {
                using (SqlConnection oconnection = new SqlConnection(Connection.cn))
                {
                    SqlCommand cmd = new SqlCommand("sp_EditBrand", oconnection);
                    cmd.Parameters.AddWithValue("IdBrand", brandToEdit.IdBrand);
                    cmd.Parameters.AddWithValue("Description", brandToEdit.Description);
                    cmd.Parameters.AddWithValue("Active", brandToEdit.Active);
                    cmd.Parameters.Add("Result", SqlDbType.Bit).Direction = ParameterDirection.Output;
                    cmd.Parameters.Add("Message", SqlDbType.VarChar, 500).Direction = ParameterDirection.Output;
                    cmd.CommandType = CommandType.StoredProcedure;

                    oconnection.Open();

                    cmd.ExecuteNonQuery();

                    result = Convert.ToBoolean(cmd.Parameters["Result"].Value);
                    Message = cmd.Parameters["Message"].ToString();
                }
            }
            catch (Exception e)
            {
                result = false;
                Message = e.Message;
            }
            return result;
        }

        public bool DeleteBrand(int idBrandToDelete, out string Message)
        {
            bool result = false;
            Message = string.Empty;
            try
            {
                using (SqlConnection oconnection = new SqlConnection(Connection.cn))
                {
                    SqlCommand cmd = new SqlCommand("sp_DeleteBrand", oconnection);
                    cmd.Parameters.AddWithValue("IdBrand", idBrandToDelete);
                    cmd.Parameters.Add("Result", SqlDbType.Bit).Direction = ParameterDirection.Output;
                    cmd.Parameters.Add("Message", SqlDbType.VarChar, 500).Direction = ParameterDirection.Output;
                    cmd.CommandType = CommandType.StoredProcedure;

                    oconnection.Open();

                    cmd.ExecuteNonQuery();

                    result = Convert.ToBoolean(cmd.Parameters["Result"].Value);
                    Message = cmd.Parameters["Message"].ToString();
                }
            }
            catch (Exception e)
            {
                result = false;
                Message = e.Message;
            }
            return result;
        }

    }
}
